In [2]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle

In [3]:
!kaggle datasets download uciml/red-wine-quality-cortez-et-al-2009

Dataset URL: https://www.kaggle.com/datasets/uciml/red-wine-quality-cortez-et-al-2009
License(s): DbCL-1.0
  0% 0.00/25.6k [00:00<?, ?B/s]
100% 25.6k/25.6k [00:00<00:00, 76.1MB/s]


In [4]:
import zipfile
zip_ref = zipfile.ZipFile('/content/red-wine-quality-cortez-et-al-2009.zip','r')
zip_ref.extractall('/content')
zip_ref.close()

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv('/content/winequality-red.csv')
df.sample(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
935             8.8              0.30         0.38             2.3      0.060   
748             7.2              0.50         0.18             2.1      0.071   
811            12.9              0.50         0.55             2.8      0.072   
541             9.5              0.46         0.49             6.3      0.064   
1117            7.0              0.69         0.07             2.5      0.091   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
935                  19.0                  72.0  0.99543  3.39       0.72   
748                  12.0                  31.0  0.99761  3.52       0.72   
811                   7.0                  24.0  1.00012  3.09       0.68   
541                   5.0                  17.0  0.99880  3.21       0.73   
1117                 15.0                  21.0  0.99572  3.38       0.60   

      alcohol  quality  
935      11.8        6  
748       9.6        6  
811      10.9        6  
541      11.0        6  
1117     11.3        6

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [11]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [12]:
df.shape

(1599, 12)

In [13]:
df.size

19188

In [14]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [15]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [16]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

Using sklearn's Linear Regression

In [21]:
import sklearn

In [23]:
x = df.iloc[:,0:11]
y = df.iloc[:,-1]

In [24]:
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [25]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [60]:
x.shape

(1599, 11)

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,random_state=2)

In [64]:
x_train.shape

(1439, 11)

In [65]:
y_train.shape

(1439,)

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
lr = LinearRegression()

In [34]:
lr.fit(x_train,y_train)

LinearRegression()

In [66]:
y_pred = lr.predict(x_test)
y_pred

array([5.93426586, 6.23029487, 5.4634545 , 5.30858622, 5.2211287 ,
       5.82859635, 5.10540916, 5.44184857, 5.59031183, 5.66440246,
       6.00533935, 6.20802536, 5.2599222 , 5.88329109, 5.21161787,
       6.44292923, 5.86928989, 6.31359074, 5.67371562, 5.90160413,
       5.53296722, 5.61055045, 5.62606891, 6.90327091, 5.192398  ,
       6.40034316, 5.21870829, 6.42768374, 6.24830926, 5.52278312,
       5.32242454, 5.80102906, 5.45146662, 6.48984383, 6.18287641,
       5.32950698, 5.87657774, 6.06184265, 5.8250589 , 5.74654534,
       5.61557168, 5.88758811, 5.76295118, 5.29594644, 5.37165713,
       6.10814631, 5.67803385, 6.19660526, 5.82667834, 5.20811849,
       5.11161678, 4.76955093, 5.27739701, 5.8181954 , 5.38143288,
       5.05951755, 5.55953253, 5.35058083, 5.7087438 , 5.81062974,
       4.88499503, 5.30008367, 5.84433368, 5.11367331, 5.80268278,
       6.15516061, 6.24930225, 6.42404009, 6.3894921 , 5.96080362,
       5.42791839, 5.44806244, 5.70466704, 5.2706709 , 5.07617

In [38]:
from sklearn.metrics import r2_score

In [40]:
r2_score(y_test,y_pred)

0.17028578036618536

In [41]:
lr.coef_

array([ 2.48332869e-02, -1.14540896e+00, -2.03245806e-01,  1.67083142e-02,
       -1.86862429e+00,  3.34080915e-03, -2.90721191e-03, -1.27620560e+01,
       -3.25275057e-01,  9.54858145e-01,  2.88058505e-01])

In [42]:
lr.intercept_

np.float64(16.466635227636743)

**Multiple Regression from scratch**

In [76]:
class MyLR:

  def __init__(self):
    self.coef_ = None
    self.intercept_ = None

  def fit(self,x_train,y_train):
    x_train = np.insert(x_train,0,1,axis=1)

    #Calculate co-eff
    betas = np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
    self.intercept_ = betas[0]
    self.coef_ = betas[1:]

  def predict(self,x_test):
    y_pred = np.dot(x_test,self.coef_) + self.intercept_
    return y_pred


This same code work in case of linear(simple)regression and multiple regression both

In [77]:
LR = MyLR()

In [78]:
LR.fit(x_train,y_train)

In [79]:
y_pred = LR.predict(x_test)
y_pred

array([5.93426586, 6.23029487, 5.4634545 , 5.30858622, 5.2211287 ,
       5.82859635, 5.10540916, 5.44184857, 5.59031183, 5.66440246,
       6.00533935, 6.20802536, 5.25992221, 5.88329109, 5.21161787,
       6.44292923, 5.86928989, 6.31359074, 5.67371562, 5.90160413,
       5.53296722, 5.61055046, 5.62606891, 6.90327091, 5.192398  ,
       6.40034316, 5.21870829, 6.42768375, 6.24830926, 5.52278312,
       5.32242454, 5.80102906, 5.45146662, 6.48984383, 6.18287642,
       5.32950698, 5.87657774, 6.06184265, 5.8250589 , 5.74654534,
       5.61557169, 5.88758811, 5.76295118, 5.29594644, 5.37165713,
       6.10814631, 5.67803385, 6.19660526, 5.82667834, 5.20811849,
       5.11161678, 4.76955093, 5.27739701, 5.8181954 , 5.38143288,
       5.05951755, 5.55953253, 5.35058083, 5.7087438 , 5.81062974,
       4.88499503, 5.30008368, 5.84433368, 5.11367331, 5.80268278,
       6.15516061, 6.24930225, 6.4240401 , 6.3894921 , 5.96080363,
       5.42791839, 5.44806244, 5.70466704, 5.2706709 , 5.07617

In [80]:
r2_score(y_test,y_pred)

0.1702857799387375

In [81]:
LR.coef_

array([ 2.48332869e-02, -1.14540896e+00, -2.03245806e-01,  1.67083142e-02,
       -1.86862429e+00,  3.34080915e-03, -2.90721191e-03, -1.27620559e+01,
       -3.25275057e-01,  9.54858145e-01,  2.88058505e-01])

In [82]:
LR.intercept_

np.float64(16.466635208427693)