In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle

In [3]:
!kaggle datasets download snmahsa/student-score-suitable-for-linear-regression

Dataset URL: https://www.kaggle.com/datasets/snmahsa/student-score-suitable-for-linear-regression
License(s): other
  0% 0.00/403 [00:00<?, ?B/s]
100% 403/403 [00:00<00:00, 1.52MB/s]


In [4]:
import zipfile
zip_ref = zipfile.ZipFile('student-score-suitable-for-linear-regression.zip','r')
zip_ref.extractall('/content')
zip_ref.close()

In [8]:
df = pd.read_csv('/content/rounded_hours_student_scores.csv')
df

Hours  Scores
0     1.1      41
1     1.2      40
2     1.4      38
3     1.5      39
4     1.6      36
5     1.8      40
6     1.9      42
7     2.1      41
8     2.2      45
9     2.3      43
10    2.5      40
11    2.6      41
12    2.7      49
13    2.9      40
14    3.0      42
15    3.2      41
16    3.3      36
17    3.4      44
18    3.6      45
19    3.7      41
20    3.8      47
21    4.0      41
22    4.1      48
23    4.3      50
24    4.4      46
25    4.5      43
26    4.7      42
27    4.8      49
28    4.9      47
29    5.1      49
30    5.2      48
31    5.4      40
32    5.5      41
33    5.6      43
34    5.8      45
35    5.9      46
36    6.0      50
37    6.2      50
38    6.3      49
39    6.5      50
40    6.6      47
41    6.7      48
42    6.9      52
43    7.0      51
44    7.1      50
45    7.3      51
46    7.4      60
47    7.6      50
48    7.7      52
49    7.8      52
50    8.0      50
51    8.1      48
52    8.2      47
53    8.4      52
54    8.5      53
55    8.7      47
56    8.8      54
57    8.9      55
58    9.1      54
59    9.2      65

In [9]:
df.shape

(60, 2)

In [10]:
df.size

120

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   60 non-null     float64
 1   Scores  60 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 1.1 KB


In [12]:
df.sample(5)

Hours  Scores
11    2.6      41
51    8.1      48
3     1.5      39
52    8.2      47
24    4.4      46

In [13]:
df.isnull().sum()

Hours     0
Scores    0
dtype: int64

In [71]:
class MyLR:

  def __init__(self):
    self.m = None
    self.b = None

  def fit(self,x_train,y_train):
    n=0  #numeritor of m
    d=0  #denominator of m

    for i in range(x_train.shape[0]):
      n = n + ((x_train[i] - x_train.mean())*(y_train[i] - y_train.mean()))
      d = d + ((x_train[i] - x_train.mean())**2)
    self.m = n/d
    self.b = y_train.mean() - (self.m * x_train.mean())
    print("m=",self.m)
    print("b=",self.b)

  def predict(self,x_test):
    return (self.m * x_test) + self.b


In [39]:
x = df.iloc[:,0].values   #.value because we are using numpy
y = df.iloc[:,1].values

In [17]:
x

array([1.1, 1.2, 1.4, 1.5, 1.6, 1.8, 1.9, 2.1, 2.2, 2.3, 2.5, 2.6, 2.7,
       2.9, 3. , 3.2, 3.3, 3.4, 3.6, 3.7, 3.8, 4. , 4.1, 4.3, 4.4, 4.5,
       4.7, 4.8, 4.9, 5.1, 5.2, 5.4, 5.5, 5.6, 5.8, 5.9, 6. , 6.2, 6.3,
       6.5, 6.6, 6.7, 6.9, 7. , 7.1, 7.3, 7.4, 7.6, 7.7, 7.8, 8. , 8.1,
       8.2, 8.4, 8.5, 8.7, 8.8, 8.9, 9.1, 9.2])

In [40]:
y

array([41, 40, 38, 39, 36, 40, 42, 41, 45, 43, 40, 41, 49, 40, 42, 41, 36,
       44, 45, 41, 47, 41, 48, 50, 46, 43, 42, 49, 47, 49, 48, 40, 41, 43,
       45, 46, 50, 50, 49, 50, 47, 48, 52, 51, 50, 51, 60, 50, 52, 52, 50,
       48, 47, 52, 53, 47, 54, 55, 54, 65])

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [21]:
x_train.shape

(48,)

In [41]:
y_train.shape

(48,)

In [81]:
LR = MyLR()   #create object lr of class MyLR

In [82]:
LR.fit(x_train, y_train)

m= 1.9710759936195263
b= 36.13000214902098


In [83]:
LR.predict(x_test)

array([47.95645811, 38.29818574, 51.1101797 , 53.27836329, 44.60562892,
       50.7159645 , 47.75935051, 45.78827452, 51.5043949 , 46.97092011,
       38.49529334, 46.37959732])

In [75]:
y_test

array([50, 41, 50, 47, 50, 60, 46, 47, 52, 41, 40, 48])

**Check by sklearn**

In [76]:
from sklearn.linear_model import LinearRegression

In [85]:
lr.fit(x_train,y_train)

m= 1.9710759936195263
b= 36.13000214902098


In [86]:
lr.predict(x_test)

array([47.95645811, 38.29818574, 51.1101797 , 53.27836329, 44.60562892,
       50.7159645 , 47.75935051, 45.78827452, 51.5043949 , 46.97092011,
       38.49529334, 46.37959732])